"""Reviewed vocabulary for the 2026-09-21 study; no inferred demand or feature truth."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from article_factory.research.service import read_json, save_json
from article_factory.research.models import validate_study

directory = Path(sys.argv[1])
study = read_json(directory / 'study.json')

notes = {
    'external': 'An architecture label in publisher copy; it does not establish safety or quality.',
    'internal': 'Use only for the architecture distinction; omit implementation and evasion instructions.',
    'compatibility': 'Name the documented game/version and check date; do not infer compatibility from a label.',
    'updates': 'Distinguish published update history from a promise about future patch speed.',
    'support': 'Compare a documented channel or policy; do not invent response-time experience.',
    'overlay': 'Describe where information appears; an overlay label does not imply aiming or firing.',
    'crosshair': 'Use in a concrete target/action example without configuration instructions.',
    'triggerbot': 'Separate the claimed firing action from aiming; compare the actual description.',
    'aimbot': 'Identify the target and claimed aiming action; do not infer a complete feature specification.',
    'aim assist': 'A broad publisher label that needs an explicit action and target.',
    'target': 'Specify the object involved, rather than treating every target as a player.',
    'firing': 'Use for the action of a shot; separate it from movement of aim.',
    'ESP': 'Use for an information-display claim; name what is displayed and where.',
    'radar': 'Describe the claimed map/display context separately from an in-world overlay.',
    'wallhack': 'Treat as a broad marketing/search label; do not assume it matches every ESP feature.',
    'visibility': 'State whose view is involved and which information is actually described.',
    'legitbot': 'Explain the naming ambiguity; the name is not evidence of safety or acceptability.',
    'prediction': 'Attribute the specific prediction claim; do not supply implementation or success rates.',
    'skin changer': 'Separate cosmetic appearance from ownership, transferability and what others see.',
    'inventory changer': 'A product label, not proof that transferable items have been acquired.',
    'inventory': 'Distinguish a local display from an account-owned item.',
    'cosmetic': 'Use for appearance; do not equate cosmetic-only marketing with a safety guarantee.',
    'client-side': 'Use only when the source states the display scope; do not generalize across products.',
    'trade': 'Treat transferability as a separate question requiring direct evidence.',
    'free trial': 'State a verified duration and restrictions; never present it as permanent free access.',
    'free version': 'Use only for a verified free tier, with its actual limitations.',
    'subscription': 'Verify duration, renewal and current price before writing an offer.',
    'features': 'Break the list into comparable actions; a longer list does not prove better performance.',
    'limitations': 'Name a sourced limit or explicit unknown; do not invent a weakness.',
    'pricing': 'Use a dated first-party offer and disclose what period/currency it covers.',
    'lineup': 'Use for a reference throw or a listed assistance feature; identify which format applies.',
    'grenade helper': 'An umbrella feature name; clarify whether the page is a reference, predictor or software offer.',
    'grenade predictor': 'Attribute the tool description and verify the supported game/version.',
    'smoke': 'Use only where a concrete reference or example involves this utility type.',
    'practice': 'Keep ordinary training tasks distinct from third-party automation.',
    'maps': 'Check the actual map coverage; do not copy old map lists as current support.',
    'detected': 'Report only as a dated, attributed publisher status, not independent verification.',
    'undetected': 'Treat as a marketing/status claim with source and date; never as a guarantee.',
    'maintenance': 'Identify the documented service/update event and its date.',
    'status': 'Name the source and timestamp; distinguish product status from player tracking.',
    'ban': 'Do not infer a ban rate, zero risk or evasion advice from isolated reports.',
    'console': 'Refer to the built-in command interface in its supported game context.',
    'sv_cheats': 'A command-reference lookup term; verify current syntax, effect and supported context before examples.',
    'server': 'Specify which controlled/practice context a command applies to.',
    'commands': 'Organize verified examples by task, effect and limits rather than a generic word list.',
    'hero scripts': 'Identify the hero and advertised automation scope; no implementation or outcome promise.',
    'macros': 'Distinguish repeating inputs from reacting to game state.',
    'bots': 'Separate community bot-development contexts from automation for a player.',
    'automation': 'Name the decision or action claimed to be delegated.',
    'Workshop': 'Attribute a specific listing and date; old listings do not prove current compatibility.',
    'custom lobby': 'State the supported practice/lobby context of any command example.',
    'Invoker': 'Use as a hero-specific example only where the source actually names this hero.',
    'Combo Builder': 'Treat as a publisher feature label; do not assume equivalent scope in other products.',
    'Auto-Cataclysm': 'Use as a named vendor feature only where a direct source supports it; avoid execution instructions.',
    'hotkeys': 'Separate an input-layout topic from an automated decision.',
    'cooldown': 'Mention the relevant timing concept without inventing current numeric values.',
    'input sequence': 'Use to explain repeated inputs; it does not establish game-state awareness.',
    'Meepo': 'Separate the hero-control question from a claim that software chooses actions.',
    'clones': 'Name the controlled units in a sourced example; do not provide an automation recipe.',
    'control groups': 'Use for the ordinary selection/control distinction, not an automation synonym.',
    'micro': 'Explain in plain language when needed: controlling multiple units or actions.',
    'map hack': 'Publisher wording for information features; do not infer complete hidden-world knowledge.',
    'fog of war': 'Separate normal information visibility from a vendor claim about displayed information.',
    'minimap': 'Specify the display location; it does not establish what hidden data is available.',
    'ward': 'Identify the tracked object and source; placement, detection and timers are different claims.',
    'Roshan': 'Separate a normal game-mechanic reference, timer and claimed information feature.',
    'teleport': 'Distinguish ordinary teleport mechanics from a publisher feature label.',
    'observer ward': 'Name the object precisely only when the relevant source supports it.',
    'sentry ward': 'Do not assume identical support for different ward types.',
    'ward tracker': 'Separate tracking an event, a timer and revealing an object.',
    'timer': 'Name what starts the timer and what remains unknown; avoid unsupported current timings.',
    'vision': 'State whose information is visible and on what basis.',
    'respawn': 'Use only with a verified mechanic/version or an explicitly uncertain timing window.',
    'HP': 'A claimed value display is different from a countdown; attribute the feature.',
    'teleport preview': 'Explain which event or destination is claimed; not a substitute for a TP Scroll guide.',
    'destination': 'A destination claim needs its own source, separate from a teleport-event notice.',
    'cast': 'Use for the relevant event only; do not add trigger/configuration instructions.',
    'Dodger': 'Attribute the named feature and documented scope; do not assume every projectile is covered.',
    'auto dodge': 'Clarify the claimed response and coverage without implementation details.',
    'projectile': 'Name the target/event category only when the source supports the distinction.',
    'reaction': 'Distinguish a claimed reaction from measured speed or reliability.',
    'movement': 'Separate displayed information from a movement/response claim.',
    'Melonity': 'Mapped Dota 2 product; attribute its statements and disclose commercial context when applicable.',
    'Umbrella': 'A competitor to compare by symmetric documented criteria, without invented testing.',
    'Octarine': 'Use the current first-party feature/offer source; unavailable information stays unknown.',
    'last hit': 'Separate training for the task from software claimed to perform it.',
    'deny': 'Name the specific resource/action context; do not infer support from an aimbot label.',
    'lane': 'Use for a relevant gameplay example; avoid unrelated meta or build advice.',
    'training': 'Identify what the reader practises and what feedback the tool provides.',
    'auto parry': 'Separate the ordinary parry mechanic from a claimed automated response.',
    'parry': 'Explain the mechanic with a current source; do not invent a timing window.',
    'melee': 'Use when identifying the action involved in a parry claim.',
    'timing': 'Describe the decision point without unsupported numerical precision.',
    'counterplay': 'Use only for evidence-backed ordinary game mechanics, not circumvention.',
    'soul orb': 'Identify the resource target separately from an enemy hero.',
    'soul aimbot': 'Use for the claimed soul-aiming action; do not infer firing or display support.',
    'soul triggerbot': 'Compare the publisher verbs: some descriptions combine aiming and firing.',
    'soul ESP': 'Use for soul information/highlighting; do not infer aim or firing.',
    'secure': 'Keep the soul-resource context explicit; do not match this to payment security.',
    'FOV': 'State whether the context is camera view or the aiming feature.',
    'field of view': 'A term needing context, not proof that camera and aim settings are interchangeable.',
    'camera': 'Keep ordinary camera/view questions separate from software aiming scope.',
    'hero': 'Identify a supported hero only from current documentation; no mass hero-page expansion.',
    'combo': 'Separate an ordinary sequence or synergy guide from an automation specification.',
    'ability': 'Name only documented coverage; a generic feature label does not cover all abilities.',
    'Cluster': 'Mapped CS2/Deadlock product; its page is first-party evidence of stated scope, not an independent review.',
    'Tsuki': 'Compare the exact public wording, not a presumed standardized feature name.',
    'Avalanche': 'Use the observed feature source and distinguish a description from performance evidence.',
    'sandbox': 'Use for the legitimate practice environment; verify current command support there.',
    'Valve Deadlock': 'Keep the game entity explicit; avoid unrelated games sharing the name.',
    'download': 'Describe the actual verified destination; no fake button, binary mirroring or implied free offer.',
    'official website': 'Verify destination ownership before identifying it as official.',
    'availability': 'Record source and check date; current access cannot be inferred from an old listing.'
}

groups = {
    'cs2-external': ['external', 'internal', 'compatibility', 'updates', 'overlay', 'support'],
    'cs2-triggerbot': ['triggerbot', 'aimbot', 'crosshair', 'target', 'firing', 'aim assist'],
    'cs2-esp': ['ESP', 'radar', 'wallhack', 'overlay', 'visibility', 'minimap'],
    'cs2-aimbot': ['aimbot', 'aim assist', 'legitbot', 'target', 'crosshair', 'prediction'],
    'cs2-skin-changer': ['skin changer', 'inventory changer', 'inventory', 'cosmetic', 'client-side', 'trade'],
    'cs2-free-paid': ['free trial', 'free version', 'subscription', 'limitations', 'support', 'updates'],
    'cs2-comparison': ['features', 'limitations', 'support', 'pricing', 'updates', 'Cluster'],
    'cs2-grenade-helper': ['grenade helper', 'lineup', 'grenade predictor', 'smoke', 'practice', 'maps'],
    'cs2-status': ['status', 'detected', 'undetected', 'maintenance', 'updates', 'ban'],
    'cs2-commands': ['console', 'sv_cheats', 'practice', 'server', 'commands'],
    'dota2-scripts': ['hero scripts', 'macros', 'bots', 'automation', 'Workshop', 'custom lobby'],
    'dota2-invoker': ['Invoker', 'Combo Builder', 'Auto-Cataclysm', 'hotkeys', 'cooldown', 'input sequence'],
    'dota2-meepo': ['Meepo', 'clones', 'control groups', 'micro', 'hero scripts', 'target'],
    'dota2-maphack': ['map hack', 'fog of war', 'minimap', 'ward', 'Roshan', 'teleport', 'ESP'],
    'dota2-ward-tracker': ['ward tracker', 'observer ward', 'sentry ward', 'timer', 'vision'],
    'dota2-roshan': ['Roshan', 'respawn', 'timer', 'HP', 'vision', 'ESP'],
    'dota2-teleport': ['teleport preview', 'teleport', 'destination', 'cast', 'visibility', 'minimap'],
    'dota2-auto-dodge': ['Dodger', 'auto dodge', 'projectile', 'reaction', 'movement', 'limitations'],
    'dota2-skin-changer': ['skin changer', 'inventory changer', 'cosmetic', 'client-side', 'inventory', 'trade'],
    'dota2-comparison': ['Melonity', 'Umbrella', 'Octarine', 'hero scripts', 'free trial', 'support', 'pricing'],
    'dota2-auto-last-hit': ['last hit', 'deny', 'lane', 'timing', 'training', 'automation'],
    'dota2-commands': ['custom lobby', 'console', 'commands', 'practice', 'bots'],
    'deadlock-auto-parry': ['auto parry', 'parry', 'melee', 'timing', 'reaction', 'counterplay'],
    'deadlock-souls': ['soul orb', 'soul aimbot', 'soul triggerbot', 'soul ESP', 'secure', 'deny', 'target'],
    'deadlock-esp': ['ESP', 'radar', 'overlay', 'visibility', 'minimap', 'target'],
    'deadlock-aimbot': ['aimbot', 'target', 'projectile', 'prediction', 'crosshair', 'soul orb'],
    'deadlock-fov': ['FOV', 'field of view', 'camera', 'aimbot', 'target'],
    'deadlock-combos': ['hero', 'combo', 'ability', 'cooldown', 'target', 'automation'],
    'deadlock-dodger': ['auto dodge', 'projectile', 'reaction', 'movement', 'ability', 'limitations'],
    'deadlock-comparison': ['Cluster', 'Tsuki', 'Avalanche', 'features', 'support', 'pricing', 'status'],
    'deadlock-trial': ['free trial', 'free version', 'subscription', 'limitations', 'pricing', 'availability'],
    'deadlock-commands': ['Valve Deadlock', 'sandbox', 'console', 'commands', 'practice'],
    'cs2-hub': ['aimbot', 'triggerbot', 'ESP', 'radar', 'skin changer', 'commands', 'Cluster'],
    'dota2-hub': ['hero scripts', 'map hack', 'skin changer', 'commands', 'Melonity', 'free trial'],
    'deadlock-hub': ['auto parry', 'soul aimbot', 'ESP', 'auto dodge', 'combo', 'commands', 'Cluster'],
    'cs2-free-download': ['free version', 'free trial', 'download', 'subscription', 'limitations', 'official website', 'availability'],
    'dota2-free-download': ['free version', 'free trial', 'download', 'subscription', 'limitations', 'official website', 'availability'],
    'deadlock-free-download': ['free version', 'free trial', 'download', 'subscription', 'limitations', 'official website', 'availability']
}
assert set(groups) == {c['id'] for c in study['clusters']}
for cluster in study['clusters']:
    cluster['reviewed_semantic_terms'] = [{'term': term, 'usage_note': notes[term]} for term in groups[cluster['id']]]
    if cluster['id'] == 'deadlock-souls':
        secure = next(t for t in cluster['reviewed_semantic_terms'] if t['term'] == 'secure')
        secure['source_urls'] = ['https://tsuki.gg/products/deadlock/features']
        secure['usage_note'] += ' Observed-source matching is limited to the reviewed Tsuki soul-target context; payment, build security and Secure Boot occurrences are excluded.'
    cluster['semantic_review'] = {'reviewed_at': '2026-09-21', 'basis': 'Editorial relevance to the reader job, checked against the retained corpus at build time. Zero matching documents remains explicitly unobserved.', 'not_a_quota': True}
validate_study(study)
save_json(directory / 'study.json', study)
print({'groups': len(groups), 'reviewed_vocabulary_entries': sum(map(len, groups.values()))})
